# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import foo as module_0


def test_case_0():
    a_0 = module_0.A()
    var_0 = a_0.set_x1()
    var_1 = a_0.set_x2_list()
    var_2 = a_0.set_x2()
    var_3 = a_0.set_x1()
    var_3.set_x2()


def test_case_1():
    a_0 = module_0.A()
    var_0 = a_0.set_x1()
    var_1 = a_0.baz()
    var_0.set_x1()


def test_case_2():
    a_0 = module_0.A()
    var_0 = a_0.set_x2()
    var_1 = a_0.baz()


def test_case_3():
    a_0 = module_0.A()
    a_0.bar()


def test_case_4():
    a_0 = module_0.A()
    var_0 = a_0.set_x2()
    var_1 = a_0.baz()
    var_2 = a_0.set_x2_list()


def test_case_5():
    a_0 = module_0.A()
    var_0 = a_0.set_x2()
    var_1 = a_0.baz()
    var_2 = a_0.set_x2()
    var_3 = a_0.set_x2_list()
    a_1 = module_0.A()
    var_4 = a_0.baz()
    int_0 = a_0.set_x2()
    var_3.set_x2()
